version: '3.8'

services:
  mysql:
    image: mysql:8.0 # Specify a version for better stability
    container_name: my-mysql-container
    environment:
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_DATABASE: backend_db
      MYSQL_USER: backend_db_user
      MYSQL_PASSWORD: backendPassword
    ports:
      - "3307:3306" # Host port 3307 mapped to container's port 3306
    volumes:
      - backend_db_mysql_data:/var/lib/mysql # Persistent data storage

volumes:
  backend_db_mysql_data: # Volume to persist MySQL data
